
CREATE TYPE public.app_role AS ENUM (
    'ROLE_ADMIN',
    'ROLE_USER'
);

CREATE TABLE public."follow-ups" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    date timestamp without time zone NOT NULL,
    notes text,
    completed boolean DEFAULT false NOT NULL,
    complication_id bigint,
    venous_access_id bigint
);

ALTER TABLE public."follow-ups" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follow_up_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.operators (
    id uuid NOT NULL,
    role public.app_role NOT NULL
);

CREATE TABLE public.patients (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    first_name character varying,
    last_name character varying,
    external_id character varying NOT NULL,
    ward character varying
);

CREATE TABLE public."removal-reasons" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    description character varying NOT NULL,
    complication boolean DEFAULT false NOT NULL
);

ALTER TABLE public."removal-reasons" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.removal_reason_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."venous-accesses" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    type character varying NOT NULL,
    site character varying NOT NULL,
    site_vein character varying NOT NULL,
    implant_date timestamp without time zone NOT NULL,
    removal_date timestamp without time zone,
    removed boolean DEFAULT false NOT NULL,
    patient_id uuid NOT NULL,
    implant_operator_id uuid NOT NULL,
    removal_operator_id uuid,
    removal_reason_id bigint
);

ALTER TABLE public."venous-accesses" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."venous-access_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public."follow-ups"
    ADD CONSTRAINT follow_up_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT operators_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patient_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patient_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public."removal-reasons"
    ADD CONSTRAINT removal_reason_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public."venous-accesses"
    ADD CONSTRAINT "venous-access_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."follow-ups"
    ADD CONSTRAINT "follow-up_complication_id_fkey" FOREIGN KEY (complication_id) REFERENCES public."removal-reasons"(id);

ALTER TABLE ONLY public."follow-ups"
    ADD CONSTRAINT "follow-up_venous_access_id_fkey" FOREIGN KEY (venous_access_id) REFERENCES public."venous-accesses"(id);

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT operators_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id);

ALTER TABLE ONLY public."venous-accesses"
    ADD CONSTRAINT "venous-access_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES public.patients(id);

ALTER TABLE ONLY public."venous-accesses"
    ADD CONSTRAINT "venous-access_removal_reason_id_fkey" FOREIGN KEY (removal_reason_id) REFERENCES public."removal-reasons"(id);

CREATE POLICY "default" ON public."follow-ups" TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "default" ON public.patients TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "default" ON public."removal-reasons" TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "default" ON public."venous-accesses" TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE public."follow-ups" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.operators ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."removal-reasons" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."venous-accesses" ENABLE ROW LEVEL SECURITY;
